[package]
name = "matepkg"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
serde = { version = "1.0.228", features = ["derive"] }
sha2 = "0.10.9"
tar = "0.4.44"
toml = "0.9.7"
version-compare = "0.2.0"
zstd = "0.13.3"
